export * from './config.resolver';
export * from './language.resolver';
export * from './subjects.resolver';
export * from './posts.resolver';
export * from './category.resolver';
export * from './testimonial.resolver';
export * from './webinar.resolver';
export * from './course.resolver';
export * from './tutor.resolver';
